[[pages]]
path = "/"
screenshotTimestamp = "2026-05-05T17:06:26Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/1a7c0bdf-0850-472e-ae99-15eeccdc530f/f77d5e3a-ca04-4b61-a3e8-938b76019c3a/F3Nr9Jy"
